context:
  distro: jazzy
  pkg: rosidl_pycommon
  group: rosidl
package:
  name: ros-jazzy-rosidl_pycommon
  version: 4.6.0
source:
  git: https://github.com/ros2-gbp/rosidl-release
  rev: release/jazzy/rosidl_pycommon/4.6.0-2
build:
  noarch: python
  script:
  - '[ -f $RECIPE_DIR/package.xml ] && cp -f $RECIPE_DIR/package.xml .'
  - python -m pip install . -vv --no-deps --no-build-isolation
  number: 1
requirements:
  host:
  - pip
  run:
  - python
  - ros-jazzy-rosidl_parser
tests:
- package_contents:
    files:
    - share/rosidl_pycommon/package.xml
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: Robot Operating System
  description: Common Python functions used by rosidl packages.
