context:
  distro: jazzy
  pkg: rcutils
  group: rcutils
package:
  name: ros-jazzy-rcutils
  version: 6.7.1
source:
  git: https://github.com/ros2-gbp/rcutils-release
  rev: release/jazzy/rcutils/6.7.1-1
  patches:
  - patches/remove_ament_cmake_ros.patch
build:
  number: 1
  script:
  - '[ -f $RECIPE_DIR/package.xml ] && cp -f $RECIPE_DIR/package.xml .'
  - mkdir build && cd build
  - export CFLAGS=
  - export CXXFLAGS=
  - '

    cmake .. -DCMAKE_GENERATOR=Ninja     -DCMAKE_PREFIX_PATH=$PREFIX     -DCMAKE_INSTALL_PREFIX=$PREFIX     -DBUILD_TESTING=OFF     -DBUILD_SHARED_LIBS=ON     -DCMAKE_C_FLAGS="-Dstatic_assert=_Static_assert
    -DROS_PACKAGE_NAME=$PKG_NAME"     && ninja install

    '
requirements:
  build:
  - cmake
  - ninja
  - ${{ compiler("cxx") }}
  host:
  - ros-jazzy-ament_cmake-devel
  - empy
tests:
- package_contents:
    files:
    - share/rcutils/package.xml
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: Robot Operating System
  description: Package containing various utility types and functions for C
