context:
  distro: jazzy
  pkg: rcutils
  group: rcutils
package:
  name: ros-jazzy-rcutils
  version: 6.7.1
source:
  git: https://github.com/ros2-gbp/rcutils-release
  rev: release/jazzy/rcutils/6.7.1-1
build:
  script: build.sh
  number: 1
requirements:
  build:
  - cmake
  - ninja
  - ros-jazzy-ament_cmake
  - ros-jazzy-ament_cmake_ros
  - empy
  - ${{ compiler("cxx") }}
  - ros-jazzy-ament_cmake_core
  - ros-jazzy-ament_cmake_export_dependencies
  - ros-jazzy-ament_cmake_export_definitions
  - ros-jazzy-ament_cmake_export_include_directories
  - ros-jazzy-ament_cmake_export_interfaces
  - ros-jazzy-ament_cmake_export_libraries
  - ros-jazzy-ament_cmake_export_link_flags
  - ros-jazzy-ament_cmake_export_targets
  - ros-jazzy-ament_cmake_gen_version_h
  - ros-jazzy-ament_cmake_libraries
  - ros-jazzy-ament_cmake_python
  - ros-jazzy-ament_cmake_target_dependencies
  - ros-jazzy-ament_cmake_test
  - ros-jazzy-ament_cmake_version
  - ros-jazzy-ament_cmake_gtest
  - ros-jazzy-ament_cmake_gmock
  - ros-jazzy-ament_cmake_pytest
  - ros-jazzy-domain_coordinator
  - ros-jazzy-ament_package
  - catkin_pkg
  - ros-jazzy-ament_cmake_include_directories
  - gtest
  - ros-jazzy-gtest_vendor
  - ros-jazzy-gmock_vendor
  - gmock
  - pytest
tests:
- package_contents:
    files:
    - share/rcutils/package.xml
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: Robot Operating System
  description: Package containing various utility types and functions for C
