context:
  distro: jazzy
  pkg: rosidl_cmake
  group: rosidl
package:
  name: ros-jazzy-rosidl_cmake
  version: 4.6.0
source:
  git: https://github.com/ros2-gbp/rosidl-release
  rev: release/jazzy/rosidl_cmake/4.6.0-2
build:
  script:
  - '[ -f $RECIPE_DIR/package.xml ] && cp -f $RECIPE_DIR/package.xml .'
  - mkdir build && cd build
  - export CFLAGS=
  - export CXXFLAGS=
  - cmake .. -DCMAKE_GENERATOR=Ninja         -DCMAKE_PREFIX_PATH=$PREFIX         -DCMAKE_INSTALL_PREFIX=$PREFIX         -DBUILD_TESTING=OFF         &&
    ninja install
  number: 1
  noarch: python
requirements:
  build:
  - cmake
  - ninja
  host:
  - ros-jazzy-ament_cmake-devel
  - ros-jazzy-ament_cmake_python-devel
  run:
  - ros-jazzy-rosidl_pycommon
tests:
- package_contents:
    files:
    - share/rosidl_cmake/package.xml
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: Robot Operating System
  description: The CMake functionality to invoke code generation for ROS interface
    files.
