context:
  distro: jazzy
  pkg: rosidl_runtime_c
  group: rosidl
package:
  name: ros-jazzy-rosidl_runtime_c
  version: 4.6.0
source:
  git: https://github.com/ros2-gbp/rosidl-release
  rev: release/jazzy/rosidl_runtime_c/4.6.0-2
build:
  script: build.sh
  number: 1
requirements:
  build:
  - cmake
  - ninja
  - ${{ compiler("c") }}
  host:
  - ros-jazzy-ament_cmake_ros
  - ros-jazzy-rosidl_typesupport_interface
  - ros-jazzy-rcutils
  - ros-jazzy-ament_cmake
  - ros-jazzy-ament_cmake_gmock
  - ros-jazzy-ament_cmake_gtest
  - ros-jazzy-ament_cmake_pytest
  - ros-jazzy-ament_cmake_core
  - ros-jazzy-ament_cmake_export_dependencies
  - ros-jazzy-ament_cmake_export_definitions
  - ros-jazzy-ament_cmake_export_include_directories
  - ros-jazzy-ament_cmake_export_interfaces
  - ros-jazzy-ament_cmake_export_libraries
  - ros-jazzy-ament_cmake_export_link_flags
  - ros-jazzy-ament_cmake_export_targets
  - ros-jazzy-ament_cmake_gen_version_h
  - ros-jazzy-ament_cmake_libraries
  - ros-jazzy-ament_cmake_python
  - ros-jazzy-ament_cmake_target_dependencies
  - ros-jazzy-ament_cmake_test
  - ros-jazzy-ament_cmake_version
  - ros-jazzy-gmock_vendor
  - gmock
  - gtest
  - ros-jazzy-gtest_vendor
  - pytest
  - ros-jazzy-ament_package
  - catkin_pkg
  - ros-jazzy-ament_cmake_include_directories
  - pip
  run:
  - ros-jazzy-rcutils
  ignore_run_exports:
    from_package:
    - gtest
tests:
- package_contents:
    files:
    - share/rosidl_runtime_c/package.xml
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: Robot Operating System
  description: Provides definitions, initialization and finalization functions, and
    macros for getting and working with rosidl typesupport types in C.
