context:
  distro: jazzy
  pkg: rosidl_runtime_c
  group: rosidl
recipe:
  version: 4.6.0
outputs:
- package:
    name: ros-jazzy-rosidl_runtime_c
  source:
    git: https://github.com/ros2-gbp/rosidl-release
    rev: release/jazzy/rosidl_runtime_c/4.6.0-2
    patches:
    - patches/remove_ament_cmake_ros.patch
  build:
    number: 1
    script:
    - '[ -f $RECIPE_DIR/package.xml ] && cp -f $RECIPE_DIR/package.xml .'
    - mkdir build && cd build
    - export CFLAGS=
    - export CXXFLAGS=
    - '

      cmake .. -DCMAKE_GENERATOR=Ninja     -DCMAKE_PREFIX_PATH=$PREFIX     -DCMAKE_INSTALL_PREFIX=$PREFIX     -DBUILD_TESTING=OFF     -DBUILD_SHARED_LIBS=ON     -DCMAKE_C_FLAGS="-Dstatic_assert=_Static_assert
      -DROS_PACKAGE_NAME=$PKG_NAME"     && ninja install

      '
  requirements:
    build:
    - ${{ compiler("c") }}
    host:
    - ros-jazzy-ament_cmake-devel
    - ros-jazzy-rosidl_typesupport_interface
    - ros-jazzy-rcutils
    run:
    - ros-jazzy-rcutils
  tests:
  - package_contents:
      files:
      - share/rosidl_runtime_c/package.xml
- package:
    name: ros-jazzy-rosidl_runtime_c-devel
  build:
    noarch: generic
  requirements:
    run:
    - ros-jazzy-rosidl_runtime_c
    - ros-jazzy-rosidl_typesupport_interface
    - ros-jazzy-rcutils
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: Robot Operating System
  description: Provides definitions, initialization and finalization functions, and
    macros for getting and working with rosidl typesupport types in C.
