context:
  distro: jazzy
  pkg: ament_cmake
  group: ament_cmake
recipe:
  version: 2.5.0
outputs:
- package:
    name: ros-jazzy-ament_cmake
  source:
    git: https://github.com/ros2-gbp/ament_cmake-release
    rev: release/jazzy/ament_cmake/2.5.0-2
  build:
    script:
    - '[ -f $RECIPE_DIR/package.xml ] && cp -f $RECIPE_DIR/package.xml .'
    - mkdir build && cd build
    - export CFLAGS=
    - export CXXFLAGS=
    - cmake .. -DCMAKE_GENERATOR=Ninja         -DCMAKE_PREFIX_PATH=$PREFIX         -DCMAKE_INSTALL_PREFIX=$PREFIX         -DBUILD_TESTING=OFF         &&
      ninja install
    number: 1
  requirements:
    host:
    - ros-jazzy-ament_cmake_core-devel
    - ros-jazzy-ament_cmake_export_dependencies-devel
    - ros-jazzy-ament_package
    - catkin_pkg
    - ros-jazzy-ament_cmake_libraries-devel
  tests:
  - package_contents:
      files:
      - share/ament_cmake/package.xml
- package:
    name: ros-jazzy-ament_cmake-devel
  build:
    noarch: generic
  requirements:
    run:
    - ros-jazzy-ament_cmake
    - ros-jazzy-ament_cmake_core-devel
    - ros-jazzy-ament_cmake_export_dependencies-devel
    - ros-jazzy-ament_cmake_export_definitions-devel
    - ros-jazzy-ament_cmake_export_include_directories-devel
    - ros-jazzy-ament_cmake_export_interfaces-devel
    - ros-jazzy-ament_cmake_export_libraries-devel
    - ros-jazzy-ament_cmake_export_link_flags-devel
    - ros-jazzy-ament_cmake_export_targets-devel
    - ros-jazzy-ament_cmake_gen_version_h-devel
    - ros-jazzy-ament_cmake_libraries-devel
    - ros-jazzy-ament_cmake_python-devel
    - ros-jazzy-ament_cmake_target_dependencies-devel
    - ros-jazzy-ament_cmake_test-devel
    - ros-jazzy-ament_cmake_version-devel
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: Robot Operating System
  description: The entry point package for the ament buildsystem in CMake.
