context:
  distro: jazzy
  pkg: ament_cmake_target_dependencies
  group: ament_cmake
package:
  name: ros-jazzy-ament_cmake_target_dependencies
  version: 2.5.0
source:
  git: https://github.com/ros2-gbp/ament_cmake-release
  rev: release/jazzy/ament_cmake_target_dependencies/2.5.0-2
build:
  script: mkdir build && cd build && CFLAGS='' CXXFLAGS='' cmake .. -DCMAKE_GENERATOR=Ninja
    -DCMAKE_PREFIX_PATH=$PREFIX -DCMAKE_INSTALL_PREFIX=$PREFIX -DBUILD_TESTING=OFF
    && ninja install
  number: 1
requirements:
  build:
  - cmake
  - ninja
  - ros-jazzy-ament_cmake_core
tests:
- package_contents:
    files:
    - share/ament_cmake_target_dependencies/package.xml
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: Robot Operating System
  description: The ability to add definitions, include directories and libraries of
    a package to a target in the ament buildsystem in CMake.
