context:
  distro: jazzy
  pkg: rosidl_generator_c
  group: rosidl
recipe:
  version: 4.6.0
outputs:
- package:
    name: ros-jazzy-rosidl_generator_c
  source:
    git: https://github.com/ros2-gbp/rosidl-release
    rev: release/jazzy/rosidl_generator_c/4.6.0-2
    patches:
    - patches/remove_ament_cmake_ros.patch
  build:
    script:
    - '[ -f $RECIPE_DIR/package.xml ] && cp -f $RECIPE_DIR/package.xml .'
    - mkdir build && cd build
    - export CFLAGS=
    - export CXXFLAGS=
    - cmake .. -DCMAKE_GENERATOR=Ninja         -DCMAKE_PREFIX_PATH=$PREFIX         -DCMAKE_INSTALL_PREFIX=$PREFIX         -DBUILD_TESTING=OFF         &&
      ninja install
    number: 1
    noarch: python
  requirements:
    host:
    - ros-jazzy-ament_cmake-devel
    run:
    - ros-jazzy-ament_index_python
    - ros-jazzy-rosidl_cli
    - ros-jazzy-rosidl_parser
    - ros-jazzy-rcutils
    - ros-jazzy-rosidl_generator_type_description
  tests:
  - package_contents:
      files:
      - share/rosidl_generator_c/package.xml
- package:
    name: ros-jazzy-rosidl_generator_c-devel
  build:
    noarch: generic
  requirements:
    run:
    - ros-jazzy-rosidl_generator_c
    - ros-jazzy-rosidl_pycommon
    - ros-jazzy-rosidl_cmake
    - ros-jazzy-rosidl_generator_type_description
    - ros-jazzy-rosidl_typesupport_interface
    - ros-jazzy-rcutils
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: Robot Operating System
  description: Generate the ROS interfaces in C.
