context:
  distro: jazzy
  pkg: ament_cmake_export_interfaces
  group: ament_cmake
recipe:
  version: 2.5.0
outputs:
- package:
    name: ros-jazzy-ament_cmake_export_interfaces
  source:
    git: https://github.com/ros2-gbp/ament_cmake-release
    rev: release/jazzy/ament_cmake_export_interfaces/2.5.0-2
  build:
    script:
    - '[ -f $RECIPE_DIR/package.xml ] && cp -f $RECIPE_DIR/package.xml .'
    - mkdir build && cd build
    - export CFLAGS=
    - export CXXFLAGS=
    - cmake .. -DCMAKE_GENERATOR=Ninja         -DCMAKE_PREFIX_PATH=$PREFIX         -DCMAKE_INSTALL_PREFIX=$PREFIX         -DBUILD_TESTING=OFF         &&
      ninja install
    number: 1
  requirements:
    host:
    - ros-jazzy-ament_cmake_core-devel
    - ros-jazzy-ament_package
    - catkin_pkg
  tests:
  - package_contents:
      files:
      - share/ament_cmake_export_interfaces/package.xml
- package:
    name: ros-jazzy-ament_cmake_export_interfaces-devel
  build:
    noarch: generic
  requirements:
    run:
    - ros-jazzy-ament_cmake_export_interfaces
    - ros-jazzy-ament_cmake_core-devel
    - ros-jazzy-ament_cmake_export_libraries-devel
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: Robot Operating System
  description: The ability to export interfaces to downstream packages in the ament
    buildsystem in CMake.
