context:
  distro: jazzy
  pkg: rosidl_cli
  group: rosidl
package:
  name: ros-jazzy-rosidl_cli
  version: 4.6.0
source:
  git: https://github.com/ros2-gbp/rosidl-release
  rev: release/jazzy/rosidl_cli/4.6.0-2
build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 1
requirements:
  host:
  - pip
  run:
  - python
  - argcomplete
tests:
- package_contents:
    files:
    - share/rosidl_cli/package.xml
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: Robot Operating System
  description: Command line tools for ROS interface generation.
