context:
  distro: jazzy
  pkg: rosidl_generator_cpp
  group: rosidl
recipe:
  version: 4.6.1
outputs:
- package:
    name: ros-jazzy-rosidl_generator_cpp
  source:
    git: https://github.com/ros2-gbp/rosidl-release
    rev: release/jazzy/rosidl_generator_cpp/4.6.1-1
  build:
    number: 1
    script:
    - '[ -f $RECIPE_DIR/package.xml ] && cp -f $RECIPE_DIR/package.xml .'
    - mkdir build && cd build
    - export CFLAGS=
    - export CXXFLAGS=
    - cmake .. -DCMAKE_GENERATOR=Ninja             -DCMAKE_PREFIX_PATH=$PREFIX             -DCMAKE_INSTALL_PREFIX=$PREFIX             -DBUILD_TESTING=OFF             &&
      ninja install
    noarch: python
  requirements:
    host:
    - ros-jazzy-ament_cmake-devel
    run:
    - ros-jazzy-ament_index_python
    - ros-jazzy-rosidl_cli
    - ros-jazzy-rosidl_generator_type_description
    - ros-jazzy-rosidl_parser
  tests:
  - package_contents:
      files:
      - share/rosidl_generator_cpp/package.xml
- package:
    name: ros-jazzy-rosidl_generator_cpp-devel
  build:
    noarch: generic
  requirements:
    run:
    - ros-jazzy-rosidl_generator_cpp
    - ros-jazzy-rosidl_pycommon
    - ros-jazzy-rosidl_cmake
    - ros-jazzy-rosidl_generator_c-devel
    - ros-jazzy-rosidl_runtime_cpp-devel
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: Robot Operating System
  description: Generate the ROS interfaces in C++.
