context:
  distro: jazzy
  pkg: rosidl_generator_cpp
  group: rosidl
package:
  name: ros-jazzy-rosidl_generator_cpp
  version: 4.6.1
source:
  git: https://github.com/ros2-gbp/rosidl-release
  rev: release/jazzy/rosidl_generator_cpp/4.6.1-1
build:
  script:
  - '[ -f $RECIPE_DIR/package.xml ] && cp -f $RECIPE_DIR/package.xml .'
  - mkdir build && cd build
  - export CFLAGS=
  - export CXXFLAGS=
  - cmake .. -DCMAKE_GENERATOR=Ninja                 -DCMAKE_PREFIX_PATH=$PREFIX                 -DCMAKE_INSTALL_PREFIX=$PREFIX                 -DBUILD_TESTING=OFF                 &&
    ninja install
  number: 1
requirements:
  build:
  - cmake
  - ninja
  - ros-jazzy-ament_cmake
  run:
  - ros-jazzy-ament_index_python
  - ros-jazzy-rosidl_cli
  - ros-jazzy-rosidl_generator_type_description
  - ros-jazzy-rosidl_parser
tests:
- package_contents:
    files:
    - share/rosidl_generator_cpp/package.xml
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: Robot Operating System
  description: Generate the ROS interfaces in C++.
