context:
  distro: jazzy
  pkg: rosidl_generator_type_description
  group: rosidl
package:
  name: ros-jazzy-rosidl_generator_type_description
  version: 4.6.0
source:
  git: https://github.com/ros2-gbp/rosidl-release
  rev: release/jazzy/rosidl_generator_type_description/4.6.0-2
build:
  script:
  - '[ -f $RECIPE_DIR/package.xml ] && cp -f $RECIPE_DIR/package.xml .'
  - mkdir build && cd build
  - export CFLAGS=
  - export CXXFLAGS=
  - cmake .. -DCMAKE_GENERATOR=Ninja                 -DCMAKE_PREFIX_PATH=$PREFIX                 -DCMAKE_INSTALL_PREFIX=$PREFIX                 -DBUILD_TESTING=OFF                 &&
    ninja install
  number: 1
  noarch: python
requirements:
  build:
  - cmake
  - ninja
  - ros-jazzy-ament_cmake_python
  - ros-jazzy-ament_cmake_ros
  - ros-jazzy-ament_cmake_core
  - ros-jazzy-ament_cmake
  - ros-jazzy-ament_cmake_gtest
  - ros-jazzy-ament_cmake_gmock
  - ros-jazzy-ament_cmake_pytest
  - ros-jazzy-domain_coordinator
  - ros-jazzy-ament_cmake_export_dependencies
  - ros-jazzy-ament_cmake_export_definitions
  - ros-jazzy-ament_cmake_export_include_directories
  - ros-jazzy-ament_cmake_export_interfaces
  - ros-jazzy-ament_cmake_export_libraries
  - ros-jazzy-ament_cmake_export_link_flags
  - ros-jazzy-ament_cmake_export_targets
  - ros-jazzy-ament_cmake_gen_version_h
  - ros-jazzy-ament_cmake_libraries
  - ros-jazzy-ament_cmake_target_dependencies
  - ros-jazzy-ament_cmake_test
  - ros-jazzy-ament_cmake_version
  - gtest
  - ros-jazzy-gtest_vendor
  - ros-jazzy-gmock_vendor
  - gmock
  - pytest
  - ros-jazzy-ament_cmake_include_directories
  run:
  - ros-jazzy-ament_index_python
  - ros-jazzy-rosidl_cli
  - ros-jazzy-rosidl_parser
tests:
- package_contents:
    files:
    - share/rosidl_generator_type_description/package.xml
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: Robot Operating System
  description: Generate hashes and descriptions of ROS 2 interface types, per REP-2011.
