context:
  distro: jazzy
  pkg: rosidl_parser
  group: rosidl
package:
  name: ros-jazzy-rosidl_parser
  version: 4.6.2
source:
  git: https://github.com/ros2-gbp/rosidl-release
  rev: release/jazzy/rosidl_parser/4.6.2-1
build:
  script:
  - '[ -f $RECIPE_DIR/package.xml ] && cp -f $RECIPE_DIR/package.xml .'
  - mkdir build && cd build
  - export CFLAGS=
  - export CXXFLAGS=
  - cmake .. -DCMAKE_GENERATOR=Ninja         -DCMAKE_PREFIX_PATH=$PREFIX         -DCMAKE_INSTALL_PREFIX=$PREFIX         -DBUILD_TESTING=OFF         &&
    ninja install
  number: 1
  noarch: python
requirements:
  build:
  - cmake
  - ninja
  host:
  - ros-jazzy-ament_cmake-devel
  run:
  - lark-parser
  - ros-jazzy-rosidl_adapter
tests:
- package_contents:
    files:
    - share/rosidl_parser/package.xml
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: Robot Operating System
  description: The parser for `.idl` ROS interface files.
